### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by janfreyberg** [lsgunth/pyft232#1]
Hi there,

I'm getting issues with this library - it's giving me the following errors:

`File "C:\Anaconda2\lib\site-packages\ft232\__init__.py", line 20, in <module>
    from .d2xx import list_devices
  File "C:\Anaconda2\lib\site-packages\ft232\d2xx.py", line 95, in <module>
    class D2xx(serial.FileLike):
AttributeError: 'module' object has no attribute 'FileLike'`

Help would be really appreciated - I'm currently struggling to use my USB-to-serial adapter.

**Comment by lsgunth** [comment]
Hi,

Yes, looks like pyft232 was broken with recent releases of python serial. I've committed c17a904f to fix this and released v0.5.

However, if you are just trying to use a standard USB-to-serial adapter you probably don't need this library. Python serial would be sufficient, just open the COM port that your device creates. This library just enables using the GPIO on the ft232 chips in a platform independent way.

Logan

**Comment by janfreyberg** [comment]
Hi Logan,

thanks very much. That's good to hear - pySerial wasn't working for me (it wasn't being read at the other end), but I now believe the problem may be more to do with the device at the other end than pySerial.

Cheers,
Jan
