### ISSUE TITLE
Where is source for 0.7 release on pypi?

### ISSUE THREAD

**Issue by richey-v** [lsgunth/pyft232#16]
https://pypi.org/project/pyft232/ shows release 0.7, but could not find source that lists shows 0.7 in setup.py .

I'd like to submit a fix for an issue I'm seeing in 0.7 but want to ensure I'm forking the correct source and branch.

**Comment by lsgunth** [comment]
Sorry, I guess the last commit to bump the version number wasn't pushed. You'll find it in master now.
