### ISSUE TITLE
Error `name 'ftdi' is not defined` when native library isn't installed

### ISSUE THREAD

**Issue by qwertychouskie** [lsgunth/pyft232#21]
The issue is in `pyft232/ft232/libftdi.py`, in lines 30/31 any exception loading the library is ignored, but then in line 36 it tries to use `ftdi` despite the fact that the object is not created if there is an error.  Instead, lines 30/31 should throw a meaningful exception that tells the user that the native library was not found.

**Comment by lsgunth** [comment]
Patches welcome!
