### ISSUE TITLE
Using CBUS as output

### ISSUE THREAD

**Issue by JBSchueler** [lsgunth/pyft232#7]
I am trying to use this library to access CBUS0 and CBUS1.
I copied the example and run it on my PC (windows 10).
The program runs, I see text coming out via the TX line but the CBUS doesn't change a bit.

Has the [`README.md`](https://github.com/lsgunth/pyft232/blob/master/README.md) example been tested on a windows machine?
Did I forget something?

[ftditest.zip](https://github.com/lsgunth/pyft232/files/2573648/ftditest.zip)
![image](https://user-images.githubusercontent.com/7997096/48375593-bb98c880-e6c8-11e8-9d74-4e8235fc2634.png)

**Comment by lsgunth** [comment]
Yes, it's been tested in windows, however that was a very long time ago.

Have you set the cbus bits in the eeprom using the FT_PROG?

Logan

**Comment by JBSchueler** [comment]
Yes, I tried `BitBang WRn`.
But I am not sure what to use.

What I noticed is when I change e.g. `CBUS0` to `BitBang WRn` and program the EEprom via 
![image](https://user-images.githubusercontent.com/7997096/48404332-482aa180-e730-11e8-9134-2f6f12a53b7e.png), unplug and replug the USB, CBUS has it's default value again (in my case `TXLED#`)

![image](https://user-images.githubusercontent.com/7997096/48404463-8b851000-e730-11e8-883d-f3ac067ff4f7.png)

**Comment by JBSchueler** [comment]
Seems the chip I am using is a "fake" one....
I am not able to change the settings of the EEPROM.

**Comment by JBSchueler** [comment]
How to determine if your FTDI chip is fake.

If the serial is `A50285BI`, it is a fake one.
There is not even an EEPROM within this chip, although it says `93C56 EEPROM`.
![image](https://user-images.githubusercontent.com/7997096/48444927-9920b100-e795-11e8-822a-a94e3a5b14f9.png)

The only way to make it work is to use an official FTDI chip.
And if you want to use your breakout board, this means that you have to replace the FTDI chip.

Russell Graves spend a [blog](https://syonyk.blogspot.com/2017/03/fixing-fake-ftdi-ft232rl-adapters-ssop.html) on this topic and how to change the chips.

**Comment by lsgunth** [comment]
Ah, good to know. Thanks for the information. I suspect you were supposed to use I/O mode, but it's been a long time and I can't remember for sure.

Logan
