### ISSUE TITLE
Error cbus_read

### ISSUE THREAD

**Issue by JBSchueler** [lsgunth/pyft232#9]
When I try to run my code I get an erro when reading the CBUS bits...

```
    CBUS = sp.cbus_read()
  File "C:\Users\bsc\AppData\Local\Programs\Python\Python37\lib\site-packages\ft232\d2xx.py", line 374, in cbus_read
    return inputs & 0xf
TypeError: unsupported operand type(s) for &: 'c_char' and 'int'
```

looking at the code of `d2xx.py` line 374
```python
def cbus_read(self):
        inputs = c.c_char()
        status = d2xx.FT_GetBitMode(self.handle, c.byref(inputs))
        if status != FT_OK: raise D2XXException(status)

        return inputs & 0xf
```

changing the return function doesn't help as expected...
```python
        return int(inputs) & 0xf
```
result
```
ValueError: invalid literal for int() with base 10: b'\xff'
```

I am not able to find the corrent way to return a value.

**Comment by lsgunth** [comment]
Hmm, yeah this probably broke with python3. I don't have a setup to test this right now but if you can try

`return inputs.value[0] & 0xf`

I think it should work. 

Also, I'd really appreciate it Ii you can submit a PR with the fix(es) once you get it working again.

Thanks,

Logan

**Comment by JBSchueler** [comment]
Thank you, your suggestion solved the issue

I will send a pull request
